version: '3.8'

services:
  node-js:
    container_name: node-js
    build: .Dockerfile
    ports:
      - 8000:8000
    command: npm run dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
    